services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${mydatabase}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '5432'

  minio:
    image: quay.io/minio/minio
    container_name: minio_server
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /path/to/your/data:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
#  qdrant:
#    image: 'qdrant/qdrant:latest'
#    ports:
#      - '6334'
